// Deterministic seed for the event analytics prototype (R6): a few hundred
// product events (page views and signups) across two weeks, five countries
// and five traffic sources, generated by a seeded PRNG so every reset and
// every fresh database holds exactly SEED_EVENTS. The DuckDB service (D2)
// applies EVENTS_SCHEMA_SQL + EVENTS_SEED_SQL when the database has no user
// objects yet and again on every reset.
// No imports: Playwright specs and native tests use this module directly.

export const EVENT_KINDS = ["page_view", "signup"] as const;
export type EventKind = (typeof EVENT_KINDS)[number];

export const COUNTRIES = ["BR", "DE", "IN", "JP", "US"] as const;
export const SOURCES = [
  "direct",
  "email",
  "referral",
  "search",
  "social",
] as const;

/** One seeded event; `revenue` is an exact decimal string or null. */
export type SeedEvent = {
  readonly id: number;
  /** ISO date, e.g. "2026-09-01". */
  readonly day: string;
  readonly kind: EventKind;
  readonly country: (typeof COUNTRIES)[number];
  readonly source: (typeof SOURCES)[number];
  readonly userId: number;
  readonly revenue: string | null;
};

export const SEED = 20261008;
export const SEED_EVENT_COUNT = 360;
export const SEED_FIRST_DAY = "2026-09-01";
export const SEED_DAYS = 14;

/** mulberry32: a small, well-known 32-bit PRNG; same seed, same stream. */
const mulberry32 = (seed: number) => {
  let a = seed | 0;
  return (): number => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
};

const pick = <T>(
  random: () => number,
  items: readonly (readonly [T, number])[],
): T => {
  const total = items.reduce((n, [, w]) => n + w, 0);
  let x = random() * total;
  for (const [item, weight] of items) {
    x -= weight;
    if (x < 0) return item;
  }
  return items[items.length - 1][0];
};

const SOURCE_WEIGHTS = [
  ["search", 35],
  ["social", 25],
  ["direct", 20],
  ["email", 12],
  ["referral", 8],
] as const;
const COUNTRY_WEIGHTS = [
  ["US", 34],
  ["DE", 20],
  ["IN", 20],
  ["BR", 14],
  ["JP", 12],
] as const;
/** Signup probability per source, scaled per country. */
const SIGNUP_RATE = {
  direct: 0.14,
  email: 0.24,
  referral: 0.2,
  search: 0.12,
  social: 0.07,
} as const;
const COUNTRY_FACTOR = { BR: 0.8, DE: 1.2, IN: 0.7, JP: 1.0, US: 1.1 } as const;
/** Plan prices; most signups are on the free plan. */
const PLAN_WEIGHTS = [["0.00", 50], ["9.99", 32], ["29.00", 18]] as const;

const dayOf = (offset: number): string =>
  new Date(Date.parse(`${SEED_FIRST_DAY}T00:00:00Z`) + offset * 86_400_000)
    .toISOString().slice(0, 10);

/**
 * `count` events from `seed`, ordered by day; ids are 1..count in that order.
 * Pure: the same arguments always return the same rows.
 */
export const generateEvents = (
  seed = SEED,
  count = SEED_EVENT_COUNT,
): readonly SeedEvent[] => {
  const random = mulberry32(seed);
  const drafts = Array.from({ length: count }, (_, k) => {
    const offset = Math.floor(random() * SEED_DAYS);
    const source = pick(random, SOURCE_WEIGHTS);
    const country = pick(random, COUNTRY_WEIGHTS);
    const signup = random() < SIGNUP_RATE[source] * COUNTRY_FACTOR[country];
    const userId = 1000 + Math.floor(random() * 400);
    const revenue = signup ? pick(random, PLAN_WEIGHTS) : null;
    return { k, offset, source, country, signup, userId, revenue };
  });
  // Stable: equal days keep generation order.
  drafts.sort((a, b) => a.offset - b.offset || a.k - b.k);
  return drafts.map((d, i): SeedEvent => ({
    id: i + 1,
    day: dayOf(d.offset),
    kind: d.signup ? "signup" : "page_view",
    country: d.country,
    source: d.source,
    userId: d.userId,
    revenue: d.revenue,
  }));
};

export const SEED_EVENTS: readonly SeedEvent[] = generateEvents();

/**
 * The events table. Ids default to a sequence that starts after the seed, so
 * `INSERT INTO events (occurred_on, kind, ...)` typed in the shell needs no
 * id; reset recreates the sequence, so the next id is exact again.
 */
export const EVENTS_SCHEMA_SQL = `CREATE SEQUENCE events_id_seq START ${
  SEED_EVENT_COUNT + 1
};
CREATE TABLE events (
  id INTEGER PRIMARY KEY DEFAULT nextval('events_id_seq'),
  occurred_on DATE NOT NULL,
  kind VARCHAR NOT NULL CHECK (kind IN ('page_view', 'signup')),
  country VARCHAR NOT NULL,
  source VARCHAR NOT NULL,
  user_id INTEGER NOT NULL,
  revenue DECIMAL(8, 2)
)`;

const sqlString = (s: string): string => `'${s.replaceAll("'", "''")}'`;

/** One INSERT for every seed event, with explicit ids. */
export const EVENTS_SEED_SQL =
  "INSERT INTO events (id, occurred_on, kind, country, source, user_id, revenue) VALUES\n" +
  SEED_EVENTS.map((e) =>
    `  (${e.id}, DATE ${sqlString(e.day)}, ${sqlString(e.kind)}, ${
      sqlString(e.country)
    }, ${sqlString(e.source)}, ${e.userId}, ${e.revenue ?? "NULL"})`
  ).join(",\n");
